In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

base_url = 'https://www.lse.ac.uk'
courses_url = 'https://www.lse.ac.uk/Programmes/Search-courses?pageIndex='

# Getting links to websites of all undergraduate programme
programme_links = []

for page in range(1, 23):
    print(f'Scraping page {page}/22...', end='\r', flush=True)
    url = f"{courses_url}{page}"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    
    all_links = soup.find_all('a', href=True)
    
    for link in all_links:
        href = link['href']
        if href.startswith('/study-at-lse/undergraduate/'):
            full_url = base_url + href
            programme_links.append(full_url)

print('\n'+ f'Total undergraduate programmes found: {len(programme_links)}')

Scraping page 22/22...
Total undergraduate programmes found: 42

In [2]:
# Function for extraxting data of interest from websites
def scrape_programme_data(url):
    res = requests.get(url)
    if res.status_code != 200: # Needed to include due to temporary type 500 errors occuring when loading websites
        print(f"⚠️ Skipping {url} — status code {res.status_code}")
        return None
    
    soup = BeautifulSoup(res.text, 'html.parser')
    data = {}

    # Degree
    course = soup.select_one('h1 > span').get_text(strip=True)
    data['degree'] = course

    # A-level requirement
    alevel_elem = soup.select_one('#alevels > div > p')
    alevel_text = alevel_elem.get_text(strip=True).split(maxsplit=1)
    data['a_lvl_req'] = alevel_text[0].strip(',')
    if len(alevel_text) > 1: data['a_lvl_extra'] = alevel_text[1]
    else: data['a_lvl_extra'] = None

    # Modules (looping through years)
    data['modules_y1'] = []
    data['modules_y2'] = []
    data['modules_y3'] = []
    data['modules_y4'] = []
    for year in range(1, 5):  # assuming up to Year 3
        modules = soup.select(f'#year-{year} div.code')
        for module in modules:
            code = module.get_text(strip=True)
            if year == 1:
                data['modules_y1'].append(code)
            elif year == 2:
                data['modules_y2'].append(code)
            elif year == 3:
                data['modules_y3'].append(code)
            elif year == 4:
                data['modules_y4'].append(code)
        
    # Applications statistics
    nr_apps = soup.select_one("#your-application__overview .block--applications .stats")
    if nr_apps: data['nr_applications'] = nr_apps.get_text(strip=True)
    else: data['nr_applications'] = None
        
    intake = soup.select_one("#your-application__overview .block--places .stats")
    if intake: data['intake'] = intake.get_text(strip=True)
    else: data['intake'] = None
        
    ratio = soup.select_one("#your-application__overview .block--ratio .stats")
    if ratio: data['ratio'] = ratio.get_text(strip=True)
    else: data['ratio'] = None

    # Fees
    home_fee_text = soup.select_one('#fees-and-funding__home p').get_text(strip=True)
    data['home_fee'] = re.search(r'£[\d,]+', home_fee_text).group()

    # Median Salary
    salary = soup.select_one('#graduate-destinations__overview .salary')
    if salary: data['median_salary'] = salary.get_text(strip=True)
    else: data['median_salary'] = None

    return data

In [3]:
# Applying function on all websites
degrees_data = []
skipped_urls = 0

for i, url in enumerate(programme_links):
    print(f"Scraping {i+1}/{len(programme_links)}: {url}", end='\r', flush=True)
    info = scrape_programme_data(url)
    if info is None:
        skipped_urls += 1
    else:
        degrees_data.append(info)

print('\nData scraping complete\n')
if skipped_urls >= 1:
    print(f'{skipped_urls} programmes skipped in data extraction, due to website loading error (500).')

Scraping 42/42: https://www.lse.ac.uk/study-at-lse/undergraduate/llb-bachelor-of-lawsogyehavioural-scienced-with-politicsss
Data scraping complete

In [4]:
# Cleaning data from non-responsive websites & converting to Dataframe
degrees_data_clean = [d for d in degrees_data if d is not None]
degrees_df = pd.DataFrame(degrees_data_clean)
degrees_df

,degree,a_lvl_req,a_lvl_extra,modules_y1,modules_y2,modules_y3,modules_y4,nr_applications,intake,ratio,home_fee,median_salary
0,BA Anthropology and Law,AAB,None,"[LL141, AN100, AN101, LL142, LL108, LL100, LL1...","[AN253, AN379, LL106, LL143, LL200]",[LL276],[],250,20,13:1,"£9,535","£34,500"
1,BA Geography,AAA,None,"[GY100, GY140, GY144, LSE100]","[GY245, GY246, GY212, GY204, GY206, GY207]",[GY350],[],377,38,10:1,"£9,535","£35,000"
2,BA History,AAA,None,"[HY120, LSE100, EH101, HY113, HY116, HY118]",[],[HY300],[],503,58,9:1,"£9,535","£35,000"
3,BA Social Anthropology,AAB,None,"[AN100, AN101, AN102, LSE100]","[AN286, AN253, AN256, AN273, AN285, AN287, AN2...",[AN397],[],232,30,8:1,"£9,535","£34,500"
4,BSc Accounting and Finance,AAA,with A in Mathematics,"[LSE100, AC105, AC106, ST107, FM101, EC1A3, EC...","[AC205, AC206, FM210, FM211, FM214, FM215, EC2...","[AC331, AC311, FM310, FM311]",[],2283,140,16:1,"£9,535","£35,000"
5,BSc Actuarial Science,A*AA,with an A* in Mathematics,"[ST102, MA100, EC1A3, EC1B3, LSE100]","[ST206, ST216, MA221, MA222, ST226, ST227]","[ST302, ST301]",[],615,68,9:1,"£9,535","£36,500"
6,BSc Data Science,A*AA,with an A* in Mathematics,"[ST102, MA100, ST101, ST115, LSE100, AC102, AC...","[ST206, ST211, ST207, MA214, MA222, MA102, MA2...","[ST310, ST311, ST312, ST300, ST301, ST302, ST3...",[],633,32,20:1,"£9,535","£36,500"
7,BSc Econometrics and Mathematical Economics,A*AA,with an A* in Mathematics,"[EC1P1, MA108, ST109, EC1A1, EC1B1, EC1C1, LSE...","[EC2A1, EC2B1, EC2C1, EH238, FM214, FM215]","[EC319, EC333, EC336, EC337, EC311]",[],None,None,None,"£9,535","£55,000"
8,BSc Economic History,AAA,including Economics or History,"[EH101, EC1A5, EC1B5, EH102, LSE100]",[EH237],[EH390],[],267,29,9:1,"£9,535","£35,000"
9,BSc Economic History and Geography,AAB,including Economics or History,"[EH101, GY100, GY140, LSE100, EC1A3, EC1A5, EC...","[GY209, GY210, EH237]","[GY313, GY314, EH308, EH390]",[],175,6,29:1,"£9,535","£35,000"
10,BSc Economics,A*AA,with an A* in Mathematics,"[EC1P1, MA108, ST109, EC1A1, EC1B1, EC1C1, LSE...","[EC2A1, EC2B1, EC2C1, EH238, FM214, FM215]",[],[],3731,225,17:1,"£9,535","£55,000"
11,BSc Economics and Data Science,A*AA,with an A* in Mathematics,"[EC1A3, EC1B3, MA100, ST102, ST101, ST115, LSE...","[EC2A3, EC2B3, EC2C3, ST206, EC2C4, ST211, ST2...","[ST310, ST311, EC302, EC307, EC310, EC311, EC3...",[],None,None,None,"£9,535","£36,500"
12,BSc Economics and Economic History,AAA,"including Economics or History, and an A in Ma...","[EH101, MA107, ST107, EC1A3, EC1B3, EH102, LSE...","[EC2A3, EC2B3, EC2C3, EC2C4, EH237]",[EH390],[],434,38,11:1,"£9,535","£35,000"
13,BSc Environment and Sustainable Development,AAA,None,"[GY120, GY121, GY100, LSE100]","[GY202, GY248, GY220]",[],[],206,8,26:1,"£9,535","£35,000"
14,BSc Environment and Sustainable Development wi...,AAA,with an A in Mathematics,"[GY120, GY121, MA107, ST107, EC1A3, EC1B3, LSE...","[GY220, GY222, EC2A3, EC2B3, EC2C3]",[],[],273,18,15:1,"£9,535","£35,000"
15,BSc Finance,A*AA,with an A* in Mathematics,"[FM100, EC1A3, EC1B3, ST102, FM102, MA108, LSE...","[FM214, FM215, FM200, FM201, EC2A3, EC2C3, EC2...","[FM301, FM302, FM321, FM322, FM304, FM305]",[],1113,56,20:1,"£9,535","£65,000"
16,BSc Financial Mathematics and Statistics,A*AA,with an A* in Mathematics,"[EC1A3, EC1B3, ST102, MA100, MA103, LSE100]","[FM214, FM215, MA221, MA222, ST202, MA203, ST213]","[FM321, FM322, MA323, ST326, MA321, MA322, ST3...",[],494,29,17:1,"£9,535","£40,000"
17,BSc Geography with Economics,AAA,including an A in Mathematics,"[EC1A3, EC1B3, MA107, ST107, GY100, LSE100, GY...","[EC2A3, GY209, GY210, GY245, GY247, EC2B3, EC2C3]","[GY313, GY314]",[],272,27,10:1,"£9,535","£35,000"
18,BSc History and Politics,AAA,None,"[GV100, GV101, LSE100, HY113, HY116, HY118, HY...",[],"[GV390, HY300]",[],412,25,16:1,"£9,535","£35,000"
19,BSc International Relations,AAA,None,"[IR100, IR101, LSE100, IR102, HY113, HY116]","[IR200, IR202, IR203, IR205, IR206]",[],[],758,50,15:1,"£9,535","£27,500"
20,BSc International Relations and Chinese,AAA,None,"[IR100, LN115, IR102, LSE100, HY113, HY116, LN...","[LN241, LN140, LN240, IR200, IR202, IR203, IR2...",[],"[LN342, LN341, IR398]",111,9,12:1,"£9,535",None
21,BSc International Relations and History,AAA,None,"[IR100, LSE100, HY120, HY113, HY116, HY118]",[],[HY300],[],260,31,8:1,"£9,535","£35,000"
22,BSc International Social and Public Policy,AAB,None,"[SP100, SP101, SP111, SP112, LSE100]","[SP200, SP201, SP210]",[SP399],[],253,23,11:1,"£9,535","£32,000"
23,BSc International Social and Public Policy wit...,AAB,with an A in Mathematics,"[SP100, SP101, MA107, ST107, EC1A3, EC1B3, LSE...","[SP200, SP201, EC2A3, EC2B3, EC2C3]","[SP399, EC325]",[],515,25,21:1,"£9,535","£32,000"
24,BSc International Social and Public Policy wit...,AAB,None,"[SP100, SP101, GV101, GV100, LSE100]","[SP200, SP201]",[SP399],[],238,9,26:1,"£9,535","£32,000"
25,"BSc Language, Culture and Society",AAB,None,"[SO100, SO110, LSE100, LN250, LN115]","[SO201, LN251, LN254, LN270]",[],"[LN252, LN253, LN270]",213,15,14:1,"£9,535",None
26,BSc Management,AAA,including an A in Mathematics,"[AC102, AC103, FM101, EC1A3, EC1B3, MA107, ST1...","[MG207, MG205, MG212, MG213, MG214]",[MG301],[],2123,138,15:1,"£9,535","£35,500"
27,BSc Mathematics and Economics,A*AA,with an A* in Mathematics,"[EC1A3, EC1B3, MA100, ST102, MA103, LSE100]","[EC2A3, EC2B3, MA221, MA222, MA203, MA208, MA2...",[],[],765,60,13:1,"£9,535","£40,000"
28,BSc Mathematics with Data Science,A*AA,with an A* in Mathematics,"[EC1A3, ST101W, MA100, ST102, MA103, LSE100]","[MA214, MA221, MA222, MA203, MA208, MA209, MA2...","[MA316, MA320, MA333, MA324, MA310, ST311, ST313]",[],482,21,23:1,"£9,535","£40,000"
29,BSc Mathematics with Economics,A*AA,with an A* in Mathematics,"[EC1A3, EC1B3, MA100, ST102, MA103, LSE100]","[EC2A3, EC2B3, MA221, MA222, MA203, MA208, MA2...",[],[],380,37,10:1,"£9,535","£40,000"
30,"BSc Mathematics, Statistics and Business",A*AA,with an A* in Mathematics,"[ST102, MA100, EC1A3, LSE100, EC1B3, FM101, MA...","[MA221, MA222, ST206, ST211, MA203, MA208, MA2...",[],[],721,43,17:1,"£9,535","£36,500"
31,BSc Philosophy and Economics,AAA,with an A in Mathematics,"[EC1A3, EC1B3, PH103, LSE100, MA107, ST107, PH...","[EC2A3, EC2B3, EC2C3, EC2C4, PH111, PH112]",[PH311],[],334,38,9:1,"£9,535","£36,500"
32,"BSc Philosophy, Logic and Scientific Method",AAA,None,"[PH103, PH111, LSE100, PH105, PH112]",[PH201],[],[],179,11,16:1,"£9,535","£36,500"
33,"BSc Philosophy, Politics and Economics",A*AA,with an A* in Mathematics,"[PH103, GV101, EC1A3, EC1B3, LSE100, ST107, MA...","[GV100, EC241, PH111, EC2A3, EC2B3, ST102, GV2...",[PH344],"[PH341, GV344, GV343]",1094,39,28:1,"£9,535","£36,500"
34,BSc Politics,AAA,None,"[GV100, GV101, LSE100]",[],[GV390],[],308,33,9:1,"£9,535","£35,500"
35,BSc Politics and Economics,AAA,including Mathematics,"[GV100, GV101, EC1A3, EC1B3, MA107, ST107, LSE...","[EC2A3, EC2B3, EC2C3, EC2C4]",[GV390],[],898,59,15:1,"£9,535","£35,500"
36,BSc Politics and International Relations,AAA,None,"[GV101, GV100, IR100, LSE100]","[IR200, IR202, IR203, IR205, IR206]","[GV390, IR398]",[],1112,37,30:1,"£9,535","£35,500"
37,BSc Politics and Philosophy,AAA,None,"[GV100, GV101, PH103, PH111, LSE100, PH112, PH...","[PH214, GV262, PH226, PH201]","[PH222, GV390, PH399]",[],319,33,10:1,"£9,535","£35,500"
38,BSc Psychological and Behavioural Science,A*AA,"including at least one of Biology, Chemistry, ...","[PB101, PB100, PB130, LSE100]","[PB230, PB200, PB201, PB202, PB204, PB205]","[PB310, PB300, DS202]",[],917,51,18:1,"£9,535","£39,000"
39,BSc Social Anthropology,AAB,None,"[AN100, AN101, AN102, LSE100]","[AN286, AN253, AN256, AN273, AN285, AN287, AN2...",[AN397],[],105,20,5:1,"£9,535","£34,500"
40,BSc Sociology,AAB,None,"[SO100, SO110, SO102, LSE100]","[SO201, SO221]",[SO302],[],528,36,15:1,"£9,535","£30,000"
41,LLB Bachelor of Laws,A*AA,None,"[LL141, LL142, LL143, LL106, LL108, LL100, LL1...","[LL276, LL200]",[],[],2964,170,17:1,"£9,535","£36,500"

In [5]:
# Saving as CSV file
degrees_df.to_csv('data/degrees/programme_data.csv', index=False)
print('Data has been saved as a CSV file')

Data has been saved as a CSV file